// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserInfoModel = "user_info"

// UserInfoModel mapped from table <user_info>
type UserInfoModel struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Username  string     `gorm:"column:username;type:varchar(100);not null" json:"username"`
	Nickname  string     `gorm:"column:nickname;type:varchar(100);not null;comment:用户昵称" json:"nickname"` // 用户昵称
	Password  string     `gorm:"column:password;type:varchar(100);not null" json:"password"`
	Avatar    string     `gorm:"column:avatar;type:varchar(255);not null" json:"avatar"`
	Gender    int32      `gorm:"column:gender;type:int;not null" json:"gender"`
	Birthday  string     `gorm:"column:birthday;type:varchar(100);not null" json:"birthday"`
	Phone     string     `gorm:"column:phone;type:varchar(11);not null;comment:手机号" json:"phone"` // 手机号
	Email     string     `gorm:"column:email;type:varchar(100);not null;comment:邮箱" json:"email"` // 邮箱
	Bio       string     `gorm:"column:bio;type:varchar(100);not null" json:"bio"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	LoginAt   *time.Time `gorm:"column:login_at;type:datetime" json:"login_at"`
	Status    int32      `gorm:"column:status;type:int;not null" json:"status"`
}

// TableName UserInfoModel's table name
func (*UserInfoModel) TableName() string {
	return TableNameUserInfoModel
}
